library(dplyr)
library(stringr)
library(here)

mround <- function(x, digits) {
  sprintf(paste0("%.", digits, "f"), round(x, digits))
}

write_tex_comment <- function(comment) {
  paste0("% ", comment) |>
    readr::write_lines(here("text", "values.tex"), append = TRUE)
}

write_tex <- function(x, macro) {
  paste0("\\newcommand{\\", macro, "}{", x, "}") |>
    readr::write_lines(here("text", "values.tex"), append = TRUE)
}

# Create values.tex file
dir.create(here("text"), showWarnings = FALSE, recursive = TRUE)
suppressWarnings(file.remove(here("text", "values.tex")))

# Write initial header comment
write_tex_comment("Analysis Values")
write_tex_comment("===================")
write_tex_comment("\n% DO NOT EDIT THIS FILE MANUALLY - IT IS AUTO-GENERATED FROM R CODE")
write_tex_comment("LaTeX: add \\input{values.tex} to the preamble (adjust path to this file for your build).")

clean_species_name <- function(species) {
  species |>
    tolower() |>
    gsub(" rockfish", "", x = _) |>
    gsub("^([a-z])", "\\U\\1", x = _, perl = TRUE) # capitalize first letter
}

# maybe todo add number of replicates
# all_fitted_results0 <- readRDS(here("data-generated", "power-results", "all-fitted-results.rds"))

# all_fitted_results0 |>
#   filter(eval_year == 2046) |>
#   group_by(species, sim_mpa_trend, sim_ar1_scenario, sampling_plan, eval_year) |>
#   summarise(reps = length(unique(replicate)), .groups = "drop") |>
#   distinct(reps, .keep_all = TRUE) |>
#   as.data.frame()


# Macro names: letters only (LaTeX multiletter names); no underscores; must not
# start with digits; avoid macros starting with `n` + letter (e.g. use Num* not
# n*) because `\n` is a TeX newline command.
path_hbll_sites <- here("data-generated", "overlays", "hbll-site-summary-table.rds")
path_fit_char <- fit_characteristics_file
path_power_df <- here("data-generated", "power-df-historical-sampling.rds")

if (all(file.exists(c(path_hbll_sites, path_fit_char, path_power_df)))) {
  write_tex_comment("\n% Power analysis values")
  write_tex_comment("-------------------")

  hbll_sites_all <- readRDS(path_hbll_sites)
  hbll_n_sites_unique <- length(unique(hbll_sites_all$`Common Site Name`))
  write_tex(as.character(hbll_n_sites_unique), "NumHbllProtectedSites")

  mean_fit_values <- readRDS(path_fit_char) |>
    filter(
      (species %in% c("canary rockfish", "silvergray rockfish") & survey %in% c("HBLL OUT N", "HBLL OUT S")) |
        !(species %in% c("canary rockfish", "silvergray rockfish"))
    ) |>
    group_by(species) |>
    summarise(across(encountered_count_per_year:sigma_E, mean))

  canary_encounter <- mean_fit_values |>
    filter(species == "canary rockfish") |>
    pull(encountered_rate_restricted)
  silvergray_encounter <- mean_fit_values |>
    filter(species == "silvergray rockfish") |>
    pull(encountered_rate_restricted)
  dogfish_encounter <- mean_fit_values |>
    filter(species == "north pacific spiny dogfish") |>
    pull(encountered_rate_restricted)

  write_tex(as.character(round(canary_encounter * 100, 0)), "CanaryEncounterRatePct")
  write_tex(as.character(round(silvergray_encounter * 100, 0)), "SilvergrayEncounterRatePct")
  write_tex(as.character(round(dogfish_encounter * 100, 0)), "DogfishEncounterRatePct")

  power_df <- readRDS(path_power_df)
  power_wide <- power_df |>
    select(species, mpa_effect_label, eval_year, power_signed) |>
    tidyr::pivot_wider(names_from = "eval_year", values_from = "power_signed")

  fmt_power_row <- function(pw) {
    pw |>
      mutate(across(where(is.numeric), \(x) sprintf("%.2f", round(x, 2))))
  }

  qb_25_power <- power_wide |>
    filter(species == "quillback rockfish", mpa_effect_label == "25%") |>
    fmt_power_row()
  ling_25_power <- power_wide |>
    filter(species == "lingcod", mpa_effect_label == "25%") |>
    fmt_power_row()
  ye_25_power <- power_wide |>
    filter(species == "yelloweye rockfish", mpa_effect_label == "25%") |>
    fmt_power_row()

  write_tex(pull(qb_25_power, "2046"), "PowerQbTwentyfiveTwentyFourtySix")
  write_tex(pull(ling_25_power, "2046"), "PowerLcTwentyfiveTwentyFourtySix")
  write_tex(pull(ye_25_power, "2046"), "PowerYeTwentyfiveTwentyFourtySix")
} else {
  write_tex_comment("\n% Power analysis skipped (HBLL overlay, fit_characteristics, or power RDS missing)")
}
